---
functional:
  - Пользователь должен иметь возможность зарегестрироваться в приложении.
  - Пользователь должен иметь возможность добавить скрипт на свой сайт.
  - На сервисе, в личном аккаунте пользователя, должны отображаться ошибки, которые нашли на сайтах пользователя.
  - Пользователь должен иметь возможность отслеживать статус ошибок, найденных на своем сайте, через сервис. #отправлено, в работе,решено, отменено, всего
  - Пользователь должен иметь возможность корректировать ошибки найденные на сайте через сервис.
  - Пользователь должен иметь возможность просматривать пространства.
  - Пользователь должен иметь возможность просматривать созданные простанства.
  - Пользователь должен иметь возможность дать имя пространству.
  - Пользователь должен иметь возможность описать пространство.
  - Пользователь должен иметь возможность добавлять пользователей в созданное пространство.
  - Должна быть возможность просматривать информацию об аккаунте.
  - Должна быть возможность изменять информацию об аккаунте #ФИО,почту, пароль
non-functional:
  - Сервис должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сервис должен быть доступен на различных устройствах.
  - Сервис должен иметь мобильную версию.
  - Сервис должен быть безопасным и защищать данные пользователя.
  - Сервис должен быть протестирован на совместимость с последними версиями браузеров.
  - Сервис должен должен быть способен обрабатывать большое количество трафика.
  - Информация на сайте должна быть представлена на русском и английском языках.
implicit:
  - Добавить функцию "теста" сервиса - новый пользователь мог бы иметь возможность сам себе отправить ошибку и посмотреть как работает сервис
  - Добавить обучающее видео по установке скрипта на свой сайт
  - Добавить обучающее видео по работе в личном кабинете пользователя
